name: Improve existing content
description: Make a suggestion to improve the content in an existing article.
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        * For questions, ask in [Discussions](https://github.com/blutui/dev.blutui.com/discussions).
        * Before you file an issue read the [Contributing guide](https://github.com/blutui/dev.blutui.com/blob/main/CONTRIBUTING.md).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/blutui/dev.blutui.com/issues).

  - type: textarea
    attributes:
      label: What article on dev.blutui.com is affected?
      description: Please link to the article you'd like to see updated.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What part(s) of the article would you like to see updated?
      description: |
        - Give as much detail as you can to help us understand the change you want to see.
        - Why should the docs be changed? What use cases does it support?
        - What is the expected outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the request here.
    validations:
      required: false
